# Generated by Django 5.2.4 on 2025-09-15 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Key name.", max_length=250, verbose_name="name"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        help_text="Hashed token.",
                        max_length=250,
                        null=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User associated with this token.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
