# Generated by Django 5.2.4 on 2025-09-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_apikey"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={"verbose_name": "API Key", "verbose_name_plural": "API Keys"},
        ),
        migrations.RemoveField(
            model_name="apikey",
            name="token",
        ),
        migrations.AddField(
            model_name="apikey",
            name="hashed_key",
            field=models.CharField(
                max_length=250, null=True, verbose_name="hashed key"
            ),
        ),
    ]
