# Generated by Django 5.2.4 on 2025-09-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_apikey_options_remove_apikey_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="expires at"
            ),
        ),
    ]
