# Generated by Django 5.2.4 on 2025-09-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_apikey_expires_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apikey",
            old_name="expires_at",
            new_name="expired_at",
        ),
    ]
