# Generated by Django 5.2.4 on 2025-09-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_expires_at_apikey_expired_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKeyPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "url_regex",
                    models.CharField(max_length=250, verbose_name="url regex"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="apikey",
            name="expired_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="expired at"
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Defines what this API key is permitted to do.",
                related_name="keys",
                to="accounts.apikeypermission",
                verbose_name="permissions",
            ),
        ),
    ]
