# Generated by Django 5.2.4 on 2025-09-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_apikeypermission_alter_apikey_expired_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikeypermission",
            name="readonly",
            field=models.BooleanField(default=False, verbose_name="readonly"),
        ),
    ]
