# Generated by Django 5.2.4 on 2025-09-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_apikeypermission_readonly"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikeypermission",
            options={
                "verbose_name": "API Key Permission",
                "verbose_name_plural": "API Key Permissions",
            },
        ),
    ]
