# Generated by Django 5.2.4 on 2025-07-28 07:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Metric slug key.", unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Metric name.", max_length=150, verbose_name="name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Metric name.",
                        max_length=150,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Metric description.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Metric description.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "value",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Metric value.", verbose_name="value"
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric",
                "verbose_name_plural": "Metrics",
            },
        ),
        migrations.CreateModel(
            name="MetricGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Goal name.", max_length=150, verbose_name="name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Goal name.",
                        max_length=150,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Goal description.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Goal description.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "value",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Goal value.", verbose_name="goal"
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        help_text="Parent metric.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="metrics.metric",
                        verbose_name="metric",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
            },
        ),
        migrations.CreateModel(
            name="MetricRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time this object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key of the metric record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        help_text="Parent metric.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="metrics.metric",
                        verbose_name="metric",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metric_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Record",
                "verbose_name_plural": "Records",
            },
        ),
    ]
