# Generated by Django 5.2.4 on 2025-09-11 09:16

import src.utils.colors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricgoal",
            name="color",
            field=models.CharField(
                default=src.utils.colors.random_hex_color,
                help_text="Goal color on the chart at statistics page.",
                max_length=7,
                verbose_name="color",
            ),
        ),
    ]
