# Generated by Django 5.2.4 on 2025-09-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_metricgoal_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricgoal",
            name="period",
            field=models.CharField(
                choices=[("YEAR", "Year"), ("MONTH", "Month"), ("WEEK", "Week")],
                default="MONTH",
                help_text="Goal period.",
                max_length=10,
                verbose_name="period",
            ),
        ),
    ]
