# Generated by Django 5.1.7 on 2025-03-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_alter_metric_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Metric description.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Metric description.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="name",
            field=models.CharField(
                default="",
                help_text="Metric name.",
                max_length=150,
                verbose_name="name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metric",
            name="name_en",
            field=models.CharField(
                help_text="Metric name.", max_length=150, null=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="Metric slug key.",
                unique=True,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="metric",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time this object was updated.",
                verbose_name="updated at",
            ),
        ),
    ]
