# Generated by Django 5.2.4 on 2025-09-12 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_metricgoal_period"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="metricgoal",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User associated with this goal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metric_goals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
