# Generated by Django 5.1.7 on 2025-03-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrics",
            "0003_metric_description_metric_description_en_metric_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="value",
            field=models.PositiveBigIntegerField(
                default=0, help_text="Metric value.", verbose_name="value"
            ),
        ),
    ]
