# Generated by Django 5.2.4 on 2025-09-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0004_metricgoal_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metric",
            name="value",
        ),
    ]
