# Generated by Django 5.1.7 on 2025-03-14 18:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0005_metricrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricrecord",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The date and time this object was created.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="metricrecord",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
