# Generated by Django 5.2.4 on 2025-09-12 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0005_remove_metric_value"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User associated with this metric.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metrics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
