# Generated by Django 5.2.4 on 2025-09-12 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0006_metric_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="user",
            field=models.ForeignKey(
                default=1,
                help_text="User associated with this metric.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="metricgoal",
            name="user",
            field=models.ForeignKey(
                default=1,
                help_text="User associated with this goal.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metric_goals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="metricrecord",
            name="user",
            field=models.ForeignKey(
                default=1,
                help_text="User associated with this record.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metric_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
            preserve_default=False,
        ),
    ]
