# Generated by Django 5.2.4 on 2025-09-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0007_alter_metric_user_alter_metricgoal_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="slug",
            field=models.SlugField(help_text="Metric slug key.", verbose_name="slug"),
        ),
    ]
