# Generated by Django 5.1.7 on 2025-03-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0007_alter_metricrecord_id_metricgoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricgoal",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Goal description.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="metricgoal",
            name="name_en",
            field=models.CharField(
                help_text="Goal name.", max_length=150, null=True, verbose_name="name"
            ),
        ),
    ]
