# Generated by Django 5.2.4 on 2025-09-22 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0008_alter_metric_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        help_text="IP address of the client.", verbose_name="IP"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="metricrecord",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client that ",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="metrics.client",
                verbose_name="client",
            ),
        ),
    ]
