# Generated by Django 5.2.4 on 2025-09-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0009_client_metricrecord_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="ip",
            field=models.GenericIPAddressField(
                db_index=True,
                help_text="IP address of the client.",
                unique=True,
                verbose_name="IP",
            ),
        ),
    ]
