# Generated by Django 5.2.4 on 2025-09-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0010_alter_client_ip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
    ]
