# Generated by Django 5.2.4 on 2025-09-22 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0011_alter_client_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metricrecord",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="metrics.client",
                verbose_name="client",
            ),
        ),
    ]
