# Generated by Django 5.1.7 on 2025-03-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0011_historicalmetric_historicalmetricgoal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmetric",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="historicalmetric",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalmetric",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="historicalmetric",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="historicalmetricgoal",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="historicalmetricgoal",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalmetricgoal",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="historicalmetricgoal",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="metric",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="metric",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="metric",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="metric",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="metricgoal",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="metricgoal",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="metricgoal",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="metricgoal",
            name="updated_by",
        ),
    ]
