# Generated by Django 5.2.4 on 2025-09-26 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0012_alter_metricrecord_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referer",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="referer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referer",
                "verbose_name_plural": "Referers",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="user_agent",
            field=models.TextField(blank=True, null=True, verbose_name="user agent"),
        ),
        migrations.AddField(
            model_name="metricrecord",
            name="referer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="metrics.referer",
                verbose_name="referer",
            ),
        ),
    ]
