# Generated by Django 5.2.4 on 2025-09-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0013_referer_client_user_agent_metricrecord_referer"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="accept_language",
            field=models.CharField(blank=True, null=True, verbose_name="language"),
        ),
    ]
