# Generated by Django 5.2.4 on 2025-09-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0014_client_accept_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="accept_language",
            new_name="language",
        ),
        migrations.AddField(
            model_name="client",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="note"),
        ),
    ]
