# Generated by Django 5.2.4 on 2025-09-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0015_rename_accept_language_client_language_client_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Country determined from IP.",
                max_length=2,
                null=True,
                verbose_name="country",
            ),
        ),
    ]
