# Generated by Django 5.2.4 on 2025-09-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="level",
        ),
        migrations.AddField(
            model_name="userskill",
            name="level",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "Beginner"),
                    ("INTERMEDIATE", "Intermediate"),
                    ("EXPERT", "Expert"),
                ],
                default="BEGINNER",
            ),
        ),
    ]
