# Generated by Django 5.2.4 on 2025-09-10 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="ended at"),
        ),
        migrations.AddField(
            model_name="project",
            name="started_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="started at"
            ),
        ),
    ]
