# Generated by Django 5.2.4 on 2025-09-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project_ended_at_project_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.ManyToManyField(
                help_text="Skills used during this project.",
                related_name="projects",
                to="portfolio.skill",
                verbose_name="skills",
            ),
        ),
    ]
