# Generated by Django 5.2.4 on 2025-09-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_project_skills"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JobArea",
            new_name="WorkArea",
        ),
    ]
