# Generated by Django 5.2.4 on 2025-09-10 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0004_project_alter_userskill_level_alter_userskill_skill_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The date and time this object was created.",
                verbose_name="created at",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time this object was updated.",
                verbose_name="updated at",
            ),
        ),
    ]
