# Generated by Django 5.2.4 on 2025-09-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_rename_jobarea_workarea"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workarea",
            name="name_en",
        ),
        migrations.AddField(
            model_name="project",
            name="areas",
            field=models.ManyToManyField(
                related_name="projects", to="portfolio.workarea"
            ),
        ),
    ]
