# Generated by Django 5.2.4 on 2025-09-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_remove_workarea_name_en_project_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="state",
            field=models.CharField(
                choices=[
                    ("FROZEN", "Frozen"),
                    ("DEVELOPMENT", "Development"),
                    ("PRODUCTION", "Production"),
                ],
                default="DEVELOPMENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("OPENSOURCE", "Open-source"),
                    ("COMMERCIAL", "Commercial"),
                    ("PET", "Pet"),
                ],
                default="PET",
                max_length=20,
            ),
        ),
    ]
