# Generated by Django 5.2.4 on 2025-09-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_project_state_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="project",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="project",
            name="version",
            field=models.CharField(default="0.0.1", max_length=20),
        ),
    ]
