# Generated by Django 5.2.4 on 2025-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_project_description_project_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workarea",
            name="name_en",
            field=models.CharField(
                help_text="The name of the job area (eg frontend, backend, etc).",
                max_length=250,
                null=True,
                verbose_name="name",
            ),
        ),
    ]
