# Generated by Django 5.2.4 on 2025-09-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_workarea_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="jobs/", verbose_name="image"
            ),
        ),
    ]
