# Generated by Django 5.2.4 on 2025-09-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_job_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="skills/", verbose_name="image"
            ),
        ),
    ]
