# Generated by Django 5.2.4 on 2025-09-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="link",
            field=models.URLField(verbose_name="link"),
        ),
    ]
