# Generated by Django 5.2.4 on 2025-09-18 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_alter_link_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(max_length=250, null=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="platforms/",
                        verbose_name="image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform",
                "verbose_name_plural": "Platforms",
            },
        ),
        migrations.AddField(
            model_name="link",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                help_text="The platform that link belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="links",
                to="portfolio.platform",
                verbose_name="platform",
            ),
        ),
    ]
