# Generated by Django 5.2.4 on 2025-09-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_platform_link_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="The priority of the link shown on the portfolio page.",
                verbose_name="priority",
            ),
        ),
    ]
