# Generated by Django 5.2.4 on 2025-09-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_link_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=100, null=True, verbose_name="slug"
            ),
        ),
    ]
