# Generated by Django 5.2.4 on 2025-09-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_platform_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="slug"),
        ),
    ]
