# Generated by Django 5.2.4 on 2025-09-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0018_alter_platform_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="workarea",
            name="slug",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="slug"
            ),
        ),
    ]
