# Generated by Django 5.2.4 on 2025-09-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_workarea_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workarea",
            name="slug",
            field=models.CharField(
                default="", max_length=250, unique=True, verbose_name="slug"
            ),
            preserve_default=False,
        ),
    ]
