# Generated by Django 5.2.4 on 2025-09-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0020_alter_workarea_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="links",
            field=models.ManyToManyField(
                help_text="Project links.",
                related_name="projects",
                to="portfolio.link",
                verbose_name="links",
            ),
        ),
    ]
