# Generated by Django 5.2.4 on 2025-09-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0021_project_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="links",
            field=models.ManyToManyField(
                blank=True,
                help_text="Project links.",
                related_name="projects",
                to="portfolio.link",
                verbose_name="links",
            ),
        ),
    ]
