# Generated by Django 5.2.4 on 2025-09-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0022_alter_project_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                ("slug", models.SlugField(max_length=250, verbose_name="slug")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="link-collections/",
                        verbose_name="image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link Collection",
                "verbose_name_plural": "Link Collections",
            },
        ),
        migrations.AlterField(
            model_name="workarea",
            name="slug",
            field=models.SlugField(max_length=250, unique=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="link",
            name="collections",
            field=models.ManyToManyField(
                blank=True,
                help_text="Collections the link belongs to (eg footer, header, project).",
                related_name="links",
                to="portfolio.linkcollection",
                verbose_name="collections",
            ),
        ),
    ]
