# Generated by Django 5.2.4 on 2025-09-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0023_linkcollection_alter_workarea_slug_link_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="link",
            name="name_en",
            field=models.CharField(max_length=250, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="linkcollection",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="linkcollection",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="linkcollection",
            name="name_en",
            field=models.CharField(max_length=250, null=True, verbose_name="name"),
        ),
    ]
