# Generated by Django 5.2.4 on 2025-09-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0024_link_description_en_link_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workarea",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="work-areas/", verbose_name="image"
            ),
        ),
    ]
