# Generated by Django 5.2.4 on 2025-09-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0026_collection_remove_link_collections_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="collections",
            field=models.ManyToManyField(
                blank=True,
                help_text="Collections the link belongs to (eg footer, header, project).",
                related_name="links",
                to="portfolio.collection",
                verbose_name="collections",
            ),
        ),
    ]
