# Generated by Django 5.2.4 on 2025-09-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0027_link_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="userskill",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="The priority of the skill shown on the portfolio page.",
                verbose_name="priority",
            ),
        ),
    ]
