# Generated by Django 5.2.4 on 2025-09-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0028_userskill_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproject",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="The priority of the portfolio shown on the portfolio page.",
                verbose_name="priority",
            ),
        ),
    ]
