# Generated by Django 5.2.4 on 2025-09-20 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0029_userproject_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="Metric slug key.", verbose_name="slug"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Metric name.", max_length=150, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Metric description.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric",
                "verbose_name_plural": "Metrics",
            },
        ),
        migrations.CreateModel(
            name="ProjectMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveBigIntegerField(default=0, verbose_name="value"),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.metric",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.project",
                        verbose_name="project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="metrics",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                through="portfolio.ProjectMetric",
                to="portfolio.metric",
            ),
        ),
    ]
