# Generated by Django 5.2.4 on 2025-09-20 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0030_metric_projectmetric_project_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio-metrics/",
                verbose_name="image",
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                help_text="The platform that metric belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metrics",
                to="portfolio.platform",
                verbose_name="platform",
            ),
        ),
    ]
