# Generated by Django 5.2.4 on 2025-09-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0031_metric_image_metric_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Metric description.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="name_en",
            field=models.CharField(
                help_text="Metric name.", max_length=150, null=True, verbose_name="name"
            ),
        ),
    ]
