# Generated by Django 5.2.4 on 2025-09-22 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0032_metric_description_en_metric_name_en"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TextBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(max_length=250, null=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Text block slug key.", verbose_name="slug"
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                ("content_en", models.TextField(null=True, verbose_name="content")),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The priority of the link shown on the portfolio page.",
                        verbose_name="priority",
                    ),
                ),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Collections the text belongs to (eg footer, header, project).",
                        related_name="texts",
                        to="portfolio.collection",
                        verbose_name="collections",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="texts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Text Block",
                "verbose_name_plural": "Text Blocks",
            },
        ),
    ]
