# Generated by Django 5.2.4 on 2025-09-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0033_textblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="textblock",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="texts/", verbose_name="image"
            ),
        ),
    ]
