# Generated by Django 5.2.4 on 2025-09-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0034_textblock_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textblock",
            name="slug",
            field=models.SlugField(
                help_text="Text block slug key.", unique=True, verbose_name="slug"
            ),
        ),
    ]
