# Generated by Django 5.2.4 on 2025-09-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0036_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=250, verbose_name="version")),
                ("file", models.FileField(upload_to="cvs/", verbose_name="cv")),
            ],
            options={
                "verbose_name": "CV",
                "verbose_name_plural": "CVs",
            },
        ),
    ]
