# Generated by Django 5.2.4 on 2025-09-23 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0037_cv"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="user",
            field=models.ForeignKey(
                default="",
                help_text="User associated with this CV.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cvs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
            preserve_default=False,
        ),
    ]
