# Generated by Django 5.2.4 on 2025-09-23 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0038_cv_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The date and time this object was created.",
                verbose_name="created at",
            ),
        ),
    ]
