# Generated by Django 5.2.4 on 2025-09-23 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0039_cv_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="file",
            field=models.FileField(
                upload_to="cvs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ("pdf", "png", "jpg", "jpeg", "docx", "doc", "txt")
                    )
                ],
                verbose_name="cv",
            ),
        ),
    ]
