# Generated by Django 6.0.8 on 2026-09-10 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0040_alter_cv_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HobbyTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the hobby tag (eg hiking, photography, etc).",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="The name of the hobby tag (eg hiking, photography, etc).",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name": "Hobby Tag",
                "verbose_name_plural": "Hobby Tags",
            },
        ),
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time this object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(max_length=250, null=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Markdown description shown in the hobby modal.",
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        help_text="Markdown description shown in the hobby modal.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="started at"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ended at"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="hobbies/", verbose_name="image"),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The priority of the hobby shown on the portfolio page.",
                        verbose_name="priority",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hobbies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="hobbies",
                        to="portfolio.hobbytag",
                        verbose_name="tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hobby",
                "verbose_name_plural": "Hobbies",
            },
        ),
    ]
